name: Deploy website

on: [push]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ">=22.12.0"
          cache: "yarn"

      - name: Install Netlify
        run: yarn add global netlify-cli


      - name: Install Dependencies
        run: yarn install 

      - name: Build Project
        run: yarn run build 
        env:
          SECRET_WEATHER_API: ${{ secrets.SECRET_WEATHER_API }}
          SECRET_IP_TOKEN: ${{ secrets.SECRET_IP_TOKEN }}

      - name: Deploy to Netlify
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then:working_dir: dir
            netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
          else
            netlify deploy --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
